Added test for AUT-3826 and added dev tags to feature files
govuk-one-login/authentication-acceptance-tests pull request #522
Opened 2024-12-19 12:46 UTC by Gosifo

## What

## How to review

## Related PRs

2024-12-19 12:57 UTC, BeckaL submitted a review, later dismissed
Looks sensible to me 👍

2024-12-19 13:34 UTC, andrew-moores requested changes
Some of the tests are double tagged with @dev.  I'll fix this and push a commit while I'm testing this in dev.

2024-12-19 16:41 UTC, andrew-moores commented
The double tagging has been resolved but will leave the PR blocked until after the code freeze.

2025-01-06 09:16 UTC, BeckaL approved these changes

2025-01-24 16:29 UTC, OlalekanAdebule commented
This test has been validated as part of AUT - 3930 and AUT - 3920 hence this PR will be closed

2025-01-24 16:29 UTC, closed without merging